package com.example.quizdladzieci;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import com.example.quizdladzieci.CalculatorContract.QestionTable;

import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.Currency;
import java.util.List;

public class CalculatorDbHelper extends SQLiteOpenHelper {
    private static final String DATABASE_NAME="CalculatorDivide.db";
    private static final int DATABASE_VERSION=2;

    private SQLiteDatabase db;

    public CalculatorDbHelper(@Nullable Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        this.db = db;

        final String SQL_CREATE_QUESTIONS_TABLE = "CREATE TABLE " +
                QestionTable.TABLE_NAME + " ( " +
                QestionTable._ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                QestionTable.COLUMN_QUESTION + " TEXT, " +
                QestionTable.COLUMN_RESULT + " INTEGER " +
                ")";

        db.execSQL(SQL_CREATE_QUESTIONS_TABLE);
        fillQuestionsTable();
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS " + QestionTable.TABLE_NAME);
        onCreate(db);
    }

    private void fillQuestionsTable(){
        DivideQuestions q1 = new DivideQuestions("100 : 10 = ", 10);
        addQuestion(q1);
        DivideQuestions q2 = new DivideQuestions("56 : 8 = ", 7);
        addQuestion(q2);
        DivideQuestions q3 = new DivideQuestions("81 : 9 = ", 9);
        addQuestion(q3);
        DivideQuestions q4 = new DivideQuestions("16 : 2 = ", 8);
        addQuestion(q4);
        DivideQuestions q5 = new DivideQuestions("18 : 6 = ", 3);
        addQuestion(q5);
        DivideQuestions q6 = new DivideQuestions("32 : 4 = ", 8);
        addQuestion(q6);
        DivideQuestions q7 = new DivideQuestions("27 : 9 = ", 3);
        addQuestion(q7);
        DivideQuestions q8 = new DivideQuestions("8 : 1 = ", 8);
        addQuestion(q8);
        DivideQuestions q9 = new DivideQuestions("45 : 5 = ", 9);
        addQuestion(q9);
        DivideQuestions q10 = new DivideQuestions("64 : 8 = ", 8);
        addQuestion(q10);
        DivideQuestions q11 = new DivideQuestions("25 : 5 = ", 5);
        addQuestion(q11);
        DivideQuestions q12 = new DivideQuestions("8 : 4 = ", 2);
        addQuestion(q12);
        DivideQuestions q13 = new DivideQuestions("10 : 2 = ", 5);
        addQuestion(q13);
        DivideQuestions q14 = new DivideQuestions("42 : 7 = ", 6);
        addQuestion(q14);
        DivideQuestions q15 = new DivideQuestions("7 : 1 = ", 7);
        addQuestion(q15);
        DivideQuestions q16 = new DivideQuestions("72 : 8 = ", 9);
        addQuestion(q16);
        DivideQuestions q17 = new DivideQuestions("12 : 3 = ", 4);
        addQuestion(q17);
        DivideQuestions q18 = new DivideQuestions("9 : 3 = ", 3);
        addQuestion(q18);
        DivideQuestions q19 = new DivideQuestions("15 : 5 = ", 3);
        addQuestion(q19);
        DivideQuestions q20 = new DivideQuestions("28 : 4 = ", 7);
        addQuestion(q20);
        DivideQuestions q21 = new DivideQuestions("60 : 6 = ", 10);
        addQuestion(q21);
        DivideQuestions q22 = new DivideQuestions("60 : 10 = ", 6);
        addQuestion(q22);
        DivideQuestions q23 = new DivideQuestions("1 : 1 = ", 1);
        addQuestion(q23);
        DivideQuestions q24 = new DivideQuestions("18 : 2 = ", 9);
        addQuestion(q24);
        DivideQuestions q25 = new DivideQuestions("16 : 8 = ", 2);
        addQuestion(q25);
        DivideQuestions q26 = new DivideQuestions("21 : 3 = ", 7);
        addQuestion(q26);
        DivideQuestions q27 = new DivideQuestions("54 : 9 = ", 6);
        addQuestion(q27);
        DivideQuestions q28 = new DivideQuestions("30 : 6 = ", 5);
        addQuestion(q28);
        DivideQuestions q29 = new DivideQuestions("56 : 7 = ", 8);
        addQuestion(q29);
        DivideQuestions q30 = new DivideQuestions("10 : 1 = ", 10);
        addQuestion(q30);
        DivideQuestions q31 = new DivideQuestions("24 : 4 = ", 6);
        addQuestion(q31);
        DivideQuestions q32 = new DivideQuestions("5 : 1 = ", 5);
        addQuestion(q32);
        DivideQuestions q33 = new DivideQuestions("48 : 6 = ", 8);
        addQuestion(q33);
        DivideQuestions q34 = new DivideQuestions("40 : 8 = ", 5);
        addQuestion(q34);
        DivideQuestions q35 = new DivideQuestions("14 : 7 = ", 2);
        addQuestion(q35);
        DivideQuestions q36 = new DivideQuestions("12 : 6 = ", 2);
        addQuestion(q36);
        DivideQuestions q37 = new DivideQuestions("63 : 9 = ", 7);
        addQuestion(q37);
        DivideQuestions q38 = new DivideQuestions("20 : 5 = ", 4);
        addQuestion(q38);
        DivideQuestions q39 = new DivideQuestions("28 : 7 = ", 4);
        addQuestion(q39);
        DivideQuestions q40 = new DivideQuestions("4 : 2 = ", 2);
        addQuestion(q40);
        DivideQuestions q41 = new DivideQuestions("36 : 4 = ", 9);
        addQuestion(q41);
        DivideQuestions q42 = new DivideQuestions("72 : 8 = ", 9);
        addQuestion(q42);
        DivideQuestions q43 = new DivideQuestions("45 : 9 = ", 5);
        addQuestion(q43);
        DivideQuestions q44 = new DivideQuestions("3 : 1 = ", 3);
        addQuestion(q44);
        DivideQuestions q45 = new DivideQuestions("14 : 2 = ", 7);
        addQuestion(q45);
        DivideQuestions q46 = new DivideQuestions("6 : 3 = ", 2);
        addQuestion(q46);
        DivideQuestions q47 = new DivideQuestions("35 : 5 = ", 7);
        addQuestion(q47);
        DivideQuestions q48 = new DivideQuestions("40 : 10 = ", 4);
        addQuestion(q48);
        DivideQuestions q49 = new DivideQuestions("27 : 3 = ", 9);
        addQuestion(q49);
        DivideQuestions q50 = new DivideQuestions("12 : 4 = ", 3);
        addQuestion(q50);
        DivideQuestions q51 = new DivideQuestions("20 : 2 = ", 10);
        addQuestion(q51);
        DivideQuestions q52 = new DivideQuestions("9 : 1 = ", 9);
        addQuestion(q52);
        DivideQuestions q53 = new DivideQuestions("2 : 2 = ", 1);
        addQuestion(q53);
        DivideQuestions q54 = new DivideQuestions("48 : 8 = ", 6);
        addQuestion(q54);
        DivideQuestions q55 = new DivideQuestions("70 : 10 = ", 7);
        addQuestion(q55);
        DivideQuestions q56 = new DivideQuestions("10 : 5 = ", 2);
        addQuestion(q56);
        DivideQuestions q57 = new DivideQuestions("80 : 8 = ", 10);
        addQuestion(q57);
        DivideQuestions q58 = new DivideQuestions("24 : 3 = ", 8);
        addQuestion(q58);
        DivideQuestions q59 = new DivideQuestions("4 : 4 = ", 1);
        addQuestion(q59);
        DivideQuestions q60 = new DivideQuestions("72 : 9 = ", 8);
        addQuestion(q60);
        DivideQuestions q61 = new DivideQuestions("18 : 3 = ", 6);
        addQuestion(q61);
        DivideQuestions q62 = new DivideQuestions("3 : 3 = ", 1);
        addQuestion(q62);
        DivideQuestions q63 = new DivideQuestions("63 : 7 = ", 9);
        addQuestion(q63);
        DivideQuestions q64 = new DivideQuestions("20 : 10 = ", 2);
        addQuestion(q64);
        DivideQuestions q65 = new DivideQuestions("6 : 2 = ", 3);
        addQuestion(q65);
        DivideQuestions q66 = new DivideQuestions("21 : 7 = ", 3);
        addQuestion(q66);
        DivideQuestions q67 = new DivideQuestions("2 : 1 = ", 2);
        addQuestion(q67);
        DivideQuestions q68 = new DivideQuestions("30 : 3 = ", 10);
        addQuestion(q68);
        DivideQuestions q69 = new DivideQuestions("40 : 5 = ", 8);
        addQuestion(q69);
        DivideQuestions q70 = new DivideQuestions("4 : 1 = ", 4);
        addQuestion(q70);
        DivideQuestions q71 = new DivideQuestions("36 : 9 = ", 4);
        addQuestion(q71);
        DivideQuestions q72 = new DivideQuestions("30 : 5 = ", 6);
        addQuestion(q72);
        DivideQuestions q73 = new DivideQuestions("32 : 8 = ", 4);
        addQuestion(q73);
        DivideQuestions q74 = new DivideQuestions("50 : 10 = ", 5);
        addQuestion(q74);
        DivideQuestions q75 = new DivideQuestions("8 : 2 = ", 4);
        addQuestion(q75);
        DivideQuestions q76 = new DivideQuestions("15 : 3 = ", 5);
        addQuestion(q76);
        DivideQuestions q77 = new DivideQuestions("24 : 8 = ", 3);
        addQuestion(q77);
        DivideQuestions q78 = new DivideQuestions("24 : 6 = ", 4);
        addQuestion(q78);
        DivideQuestions q79 = new DivideQuestions("35 : 7 = ", 5);
        addQuestion(q79);
        DivideQuestions q80 = new DivideQuestions("70 : 7 = ", 10);
        addQuestion(q80);
        DivideQuestions q81 = new DivideQuestions("42 : 6 = ", 7);
        addQuestion(q81);
        DivideQuestions q82 = new DivideQuestions("20 : 4 = ", 5);
        addQuestion(q82);
        DivideQuestions q83 = new DivideQuestions("12 : 2 = ", 6);
        addQuestion(q83);
        DivideQuestions q84 = new DivideQuestions("49 : 7 = ", 7);
        addQuestion(q84);
        DivideQuestions q85 = new DivideQuestions("36 : 6 = ", 6);
        addQuestion(q85);
        DivideQuestions q86 = new DivideQuestions("8 : 8 = ", 1);
        addQuestion(q86);
        DivideQuestions q87 = new DivideQuestions("30 : 10 = ", 3);
        addQuestion(q87);
        DivideQuestions q88 = new DivideQuestions("54 : 6 = ", 9);
        addQuestion(q88);
        DivideQuestions q89 = new DivideQuestions("40 : 4 = ", 10);
        addQuestion(q89);
        DivideQuestions q90 = new DivideQuestions("16 : 4 = ", 4);
        addQuestion(q90);
        DivideQuestions q91 = new DivideQuestions("6 : 1 = ", 6);
        addQuestion(q91);
        DivideQuestions q92 = new DivideQuestions("50 : 5 = ", 10);
        addQuestion(q92);
        DivideQuestions q93 = new DivideQuestions("48 : 6 = ", 8);
        addQuestion(q93);
        DivideQuestions q94 = new DivideQuestions("32 : 4 = ", 8);
        addQuestion(q94);
        DivideQuestions q95 = new DivideQuestions("14 : 7 = ", 2);
        addQuestion(q95);
        DivideQuestions q96 = new DivideQuestions("100 : 10 = ", 10);
        addQuestion(q96);
        DivideQuestions q97 = new DivideQuestions("12 : 4 = ", 3);
        addQuestion(q97);
        DivideQuestions q98 = new DivideQuestions("15 : 5 = ", 3);
        addQuestion(q98);
        DivideQuestions q99 = new DivideQuestions("72 : 8 = ", 8);
        addQuestion(q99);
        DivideQuestions q100 = new DivideQuestions("14 : 2 = ", 7);
        addQuestion(q100);
        DivideQuestions q101 = new DivideQuestions("48 : 8 = ", 6);
        addQuestion(q101);
        DivideQuestions q102 = new DivideQuestions("54 : 3 = ", 18);
        addQuestion(q102);
        DivideQuestions q103 = new DivideQuestions("30 : 6 = ", 5);
        addQuestion(q103);
        DivideQuestions q104 = new DivideQuestions("62 : 31 = ", 2);
        addQuestion(q104);
        DivideQuestions q105 = new DivideQuestions("90 : 6 = ", 15);
        addQuestion(q105);
        DivideQuestions q106 = new DivideQuestions("48 : 24 = ", 2);
        addQuestion(q106);
        DivideQuestions q107 = new DivideQuestions("20 : 5 = ", 4);
        addQuestion(q107);
        DivideQuestions q108 = new DivideQuestions("30 : 6 = ", 5);
        addQuestion(q108);
        DivideQuestions q109 = new DivideQuestions("66 : 22 = ", 3);
        addQuestion(q109);
        DivideQuestions q110 = new DivideQuestions("100 : 50 = ", 2);
        addQuestion(q110);
        DivideQuestions q111 = new DivideQuestions("69 : 23 = ", 3);
        addQuestion(q111);
        DivideQuestions q112 = new DivideQuestions("70 : 14 = ", 5);
        addQuestion(q112);
        DivideQuestions q113 = new DivideQuestions("48 : 8 = ", 6);
        addQuestion(q113);
        DivideQuestions q114 = new DivideQuestions("21 : 3 = ", 7);
        addQuestion(q114);
        DivideQuestions q115 = new DivideQuestions("63 : 9 = ", 7);
        addQuestion(q115);
        DivideQuestions q116 = new DivideQuestions("80 : 4 = ", 20);
        addQuestion(q116);
        DivideQuestions q117 = new DivideQuestions("72 : 6 = ", 12);
        addQuestion(q117);
        DivideQuestions q118 = new DivideQuestions("30 : 15 = ", 2);
        addQuestion(q118);
        DivideQuestions q119 = new DivideQuestions("80 : 4 = ", 20);
        addQuestion(q119);
        DivideQuestions q120 = new DivideQuestions("48 : 4 = ", 12);
        addQuestion(q120);
        DivideQuestions q121 = new DivideQuestions("92 : 4 = ", 23);
        addQuestion(q121);
        DivideQuestions q122 = new DivideQuestions("57 : 3 = ", 19);
        addQuestion(q122);
        DivideQuestions q123 = new DivideQuestions("18 : 3 = ", 6);
        addQuestion(q123);
        DivideQuestions q124 = new DivideQuestions("36 : 9 = ", 4);
        addQuestion(q124);
        DivideQuestions q125 = new DivideQuestions("87 : 29 = ", 3);
        addQuestion(q125);
        DivideQuestions q126 = new DivideQuestions("32 : 4 = ", 8);
        addQuestion(q126);
        DivideQuestions q127 = new DivideQuestions("96 : 8 = ", 12);
        addQuestion(q127);
        DivideQuestions q128 = new DivideQuestions("94 : 47 = ", 2);
        addQuestion(q128);
        DivideQuestions q129 = new DivideQuestions("48 : 12 = ", 4);
        addQuestion(q129);
        DivideQuestions q130 = new DivideQuestions("100 : 20 = ", 5);
        addQuestion(q130);
        DivideQuestions q131 = new DivideQuestions("88 : 8 = ", 11);
        addQuestion(q131);
        DivideQuestions q132 = new DivideQuestions("78 : 26 = ", 3);
        addQuestion(q132);
        DivideQuestions q133 = new DivideQuestions("98 : 14 = ", 7);
        addQuestion(q133);
        DivideQuestions q134 = new DivideQuestions("92 : 4 = ", 23);
        addQuestion(q134);
        DivideQuestions q135 = new DivideQuestions("92 : 23 = ", 4);
        addQuestion(q135);
        DivideQuestions q136 = new DivideQuestions("75 : 25 = ", 3);
        addQuestion(q136);
        DivideQuestions q137 = new DivideQuestions("48 : 12 = ", 4);
        addQuestion(q137);
        DivideQuestions q138 = new DivideQuestions("84 : 42 = ", 2);
        addQuestion(q138);
        DivideQuestions q139 = new DivideQuestions("92 : 46 = ", 2);
        addQuestion(q139);
        DivideQuestions q140 = new DivideQuestions("95 : 5 = ", 19);
        addQuestion(q140);
        DivideQuestions q141 = new DivideQuestions("33 : 3 = ", 11);
        addQuestion(q141);
        DivideQuestions q142 = new DivideQuestions("90 : 18 = ", 5);
        addQuestion(q142);
        DivideQuestions q143 = new DivideQuestions("66 : 6 = ", 11);
        addQuestion(q143);
        DivideQuestions q144 = new DivideQuestions("88 : 44 = ", 2);
        addQuestion(q144);
        DivideQuestions q145 = new DivideQuestions("48 : 6 = ", 8);
        addQuestion(q145);
        DivideQuestions q146 = new DivideQuestions("84 : 28 = ", 3);
        addQuestion(q146);
        DivideQuestions q147 = new DivideQuestions("93 : 3 = ", 31);
        addQuestion(q147);
        DivideQuestions q148 = new DivideQuestions("60 : 4 = ", 15);
        addQuestion(q148);
        DivideQuestions q149 = new DivideQuestions("70 : 14 = ", 5);
        addQuestion(q149);
        DivideQuestions q150 = new DivideQuestions("84 : 14 = ", 6);
        addQuestion(q150);
        DivideQuestions q151 = new DivideQuestions("15 : 3 = ", 5);
        addQuestion(q151);
        DivideQuestions q152 = new DivideQuestions("60 : 5 = ", 12);
        addQuestion(q152);
        DivideQuestions q153 = new DivideQuestions("88 : 8 = ", 11);
        addQuestion(q153);
        DivideQuestions q154 = new DivideQuestions("76 : 38 = ", 2);
        addQuestion(q154);
        DivideQuestions q155 = new DivideQuestions("45 : 15 = ", 3);
        addQuestion(q155);
        DivideQuestions q156 = new DivideQuestions("52 : 13 = ", 4);
        addQuestion(q156);
        DivideQuestions q157 = new DivideQuestions("54 : 9 = ", 6);
        addQuestion(q157);
        DivideQuestions q158 = new DivideQuestions("39 : 3 = ", 13);
        addQuestion(q158);
        DivideQuestions q159 = new DivideQuestions("87 : 29 = ", 3);
        addQuestion(q159);
        DivideQuestions q160 = new DivideQuestions("100 : 4 = ", 25);
        addQuestion(q160);
        DivideQuestions q161 = new DivideQuestions("96 : 16 = ", 6);
        addQuestion(q161);
        DivideQuestions q162 = new DivideQuestions("66 : 11 = ", 6);
        addQuestion(q162);
        DivideQuestions q163 = new DivideQuestions("60 : 4 = ", 15);
        addQuestion(q163);
        DivideQuestions q164 = new DivideQuestions("88 : 4 = ", 22);
        addQuestion(q164);
        DivideQuestions q165 = new DivideQuestions("87 : 3 = ", 29);
        addQuestion(q165);
        DivideQuestions q166 = new DivideQuestions("45 : 5 = ", 9);
        addQuestion(q166);
        DivideQuestions q167 = new DivideQuestions("44 : 4 = ", 11);
        addQuestion(q167);
        DivideQuestions q168 = new DivideQuestions("48 : 24 = ", 2);
        addQuestion(q168);
        DivideQuestions q169 = new DivideQuestions("80 : 40 = ", 2);
        addQuestion(q169);
        DivideQuestions q170 = new DivideQuestions("99 : 11 = ", 9);
        addQuestion(q170);
        DivideQuestions q171 = new DivideQuestions("80 : 40 = ", 2);
        addQuestion(q171);
        DivideQuestions q172 = new DivideQuestions("30 : 3 = ", 10);
        addQuestion(q172);
        DivideQuestions q173 = new DivideQuestions("40 : 5 = ", 8);
        addQuestion(q173);
        DivideQuestions q174 = new DivideQuestions("54 : 18 = ", 3);
        addQuestion(q174);
        DivideQuestions q175 = new DivideQuestions("66 : 6 = ", 11);
        addQuestion(q175);
        DivideQuestions q176 = new DivideQuestions("45 : 9 = ", 5);
        addQuestion(q176);
        DivideQuestions q177 = new DivideQuestions("68 : 17 = ", 4);
        addQuestion(q177);
        DivideQuestions q178 = new DivideQuestions("75 : 5 = ", 15);
        addQuestion(q178);
        DivideQuestions q179 = new DivideQuestions("85 : 5 = ", 17);
        addQuestion(q179);
        DivideQuestions q180 = new DivideQuestions("28 : 7 = ", 4);
        addQuestion(q180);
        DivideQuestions q181 = new DivideQuestions("16 : 4 = ", 4);
        addQuestion(q181);
        DivideQuestions q182 = new DivideQuestions("84 : 28 = ", 3);
        addQuestion(q182);
        DivideQuestions q183 = new DivideQuestions("18 : 6 = ", 3);
        addQuestion(q183);
        DivideQuestions q184 = new DivideQuestions("91 : 7 = ", 13);
        addQuestion(q184);
        DivideQuestions q185 = new DivideQuestions("64 : 32 = ", 2);
        addQuestion(q185);
        DivideQuestions q186 = new DivideQuestions("96 : 24 = ", 4);
        addQuestion(q186);
        DivideQuestions q187 = new DivideQuestions("100 : 25 = ", 4);
        addQuestion(q187);
        DivideQuestions q188 = new DivideQuestions("66 : 33 = ", 2);
        addQuestion(q188);
        DivideQuestions q189 = new DivideQuestions("35 : 7 = ", 5);
        addQuestion(q189);
        DivideQuestions q190 = new DivideQuestions("64 : 8 = ", 8);
        addQuestion(q190);
        DivideQuestions q191 = new DivideQuestions("62 : 31 = ", 2);
        addQuestion(q191);
        DivideQuestions q192 = new DivideQuestions("93 : 31 = ", 3);
        addQuestion(q192);
        DivideQuestions q193 = new DivideQuestions("45 : 3 = ", 15);
        addQuestion(q193);
        DivideQuestions q194 = new DivideQuestions("68 : 4 = ", 17);
        addQuestion(q194);
        DivideQuestions q195 = new DivideQuestions("12 : 3 = ", 4);
        addQuestion(q195);
        DivideQuestions q196 = new DivideQuestions("81 : 3 = ", 27);
        addQuestion(q196);
        DivideQuestions q197 = new DivideQuestions("72 : 24 = ", 3);
        addQuestion(q197);
        DivideQuestions q198 = new DivideQuestions("60 : 30 = ", 2);
        addQuestion(q198);
        DivideQuestions q199 = new DivideQuestions("80 : 20 = ", 4);
        addQuestion(q199);
        DivideQuestions q200 = new DivideQuestions("39 : 13 = ", 3);
        addQuestion(q200);
        DivideQuestions q201 = new DivideQuestions("45 : 15 = ", 3);
        addQuestion(q201);
        DivideQuestions q202 = new DivideQuestions("42 : 3 = ", 14);
        addQuestion(q202);
        DivideQuestions q203 = new DivideQuestions("24 : 8 = ", 3);
        addQuestion(q203);
        DivideQuestions q204 = new DivideQuestions("75 : 25 = ", 3);
        addQuestion(q204);
        DivideQuestions q205 = new DivideQuestions("56 : 8 = ", 7);
        addQuestion(q205);
        DivideQuestions q206 = new DivideQuestions("45 : 3 = ", 15);
        addQuestion(q206);
        DivideQuestions q207 = new DivideQuestions("94 : 47 = ", 2);
        addQuestion(q207);
        DivideQuestions q208 = new DivideQuestions("25 : 5 = ", 5);
        addQuestion(q208);
        DivideQuestions q209 = new DivideQuestions("81 : 27 = ", 3);
        addQuestion(q209);
        DivideQuestions q210 = new DivideQuestions("77 : 11 = ", 7);
        addQuestion(q210);
        DivideQuestions q211 = new DivideQuestions("66 : 6 = ", 11);
        addQuestion(q211);
        DivideQuestions q212 = new DivideQuestions("95 : 19 = ", 5);
        addQuestion(q212);
        DivideQuestions q213 = new DivideQuestions("33 : 11 = ", 3);
        addQuestion(q213);
        DivideQuestions q214 = new DivideQuestions("54 : 6 = ", 9);
        addQuestion(q214);
        DivideQuestions q215 = new DivideQuestions("39 : 3 = ", 13);
        addQuestion(q215);
        DivideQuestions q216 = new DivideQuestions("100 : 5 = ", 20);
        addQuestion(q216);
        DivideQuestions q217 = new DivideQuestions("72 : 3 = ", 24);
        addQuestion(q217);
        DivideQuestions q218 = new DivideQuestions("54 : 3 = ", 18);
        addQuestion(q218);
        DivideQuestions q219 = new DivideQuestions("78 : 26 = ", 3);
        addQuestion(q219);
        DivideQuestions q220 = new DivideQuestions("30 : 5 = ", 6);
        addQuestion(q220);
        DivideQuestions q221 = new DivideQuestions("55 : 5 = ", 11);
        addQuestion(q221);
        DivideQuestions q222 = new DivideQuestions("8 : 4 = ", 2);
        addQuestion(q222);
        DivideQuestions q223 = new DivideQuestions("84 : 14 = ", 6);
        addQuestion(q223);
        DivideQuestions q224 = new DivideQuestions("91 : 7 = ", 13);
        addQuestion(q224);
        DivideQuestions q225 = new DivideQuestions("92 : 4 = ", 23);
        addQuestion(q225);
        DivideQuestions q226 = new DivideQuestions("72 : 12 = ", 6);
        addQuestion(q226);
        DivideQuestions q227 = new DivideQuestions("66 : 22 = ", 3);
        addQuestion(q227);
        DivideQuestions q228 = new DivideQuestions("34 : 17 = ", 2);
        addQuestion(q228);
        DivideQuestions q229 = new DivideQuestions("18 : 9 = ", 2);
        addQuestion(q229);
        DivideQuestions q230 = new DivideQuestions("40 : 8 = ", 5);
        addQuestion(q230);
        DivideQuestions q231 = new DivideQuestions("36 : 4 = ", 9);
        addQuestion(q231);
        DivideQuestions q232 = new DivideQuestions("52 : 26 = ", 2);
        addQuestion(q232);
        DivideQuestions q233 = new DivideQuestions("45 : 3 = ", 15);
        addQuestion(q233);
        DivideQuestions q234 = new DivideQuestions("77 : 11 = ", 7);
        addQuestion(q234);
        DivideQuestions q235 = new DivideQuestions("36 : 12 = ", 3);
        addQuestion(q235);
        DivideQuestions q236 = new DivideQuestions("56 : 28 = ", 2);
        addQuestion(q236);
        DivideQuestions q237 = new DivideQuestions("72 : 4 = ", 18);
        addQuestion(q237);
        DivideQuestions q238 = new DivideQuestions("96 : 24 = ", 4);
        addQuestion(q238);
        DivideQuestions q239 = new DivideQuestions("48 : 8 = ", 6);
        addQuestion(q239);
        DivideQuestions q240 = new DivideQuestions("70 : 5 = ", 14);
        addQuestion(q240);

    }

    private void addQuestion(DivideQuestions questions){
        ContentValues cv = new ContentValues();
        cv.put(QestionTable.COLUMN_QUESTION, questions.getQuestion());
        cv.put(QestionTable.COLUMN_RESULT, questions.getResult());

        db.insert(QestionTable.TABLE_NAME, null, cv);
    }

    public List<DivideQuestions> getAllDivideQuestions() {
        List<DivideQuestions> divideQuestionsList = new ArrayList<>();
        db = getReadableDatabase();
        Cursor c = db.rawQuery("SELECT * FROM " + QestionTable.TABLE_NAME, null);
        if(c.moveToFirst()) {
            do {
                DivideQuestions questions = new DivideQuestions();
                questions.setQuestion(c.getString(c.getColumnIndex(QestionTable.COLUMN_QUESTION)));
                questions.setResult(c.getInt(c.getColumnIndex(QestionTable.COLUMN_RESULT)));
                divideQuestionsList.add(questions);
            }while(c.moveToNext());
        }
        c.close();
        return divideQuestionsList;
    }
}
