package com.example.quizdladzieci;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import com.example.quizdladzieci.CalculatorContract.QuestionRestTable;

import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.List;

public class DbHelper2 extends SQLiteOpenHelper {
    private static final String DATABASE_NAME="CalculatorDivideRest.db";
    private static final int DATABASE_VERSION=2;

    private SQLiteDatabase db;

    public DbHelper2(@Nullable Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        this.db = db;

        final String SQL_CREATE_QUESTIONS_REST_TABLE = "CREATE TABLE " +
                CalculatorContract.QuestionRestTable.TABLE_NAME + " ( " +
                CalculatorContract.QuestionRestTable._ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                CalculatorContract.QuestionRestTable.COLUMN_QUESTION + " TEXT, " +
                CalculatorContract.QuestionRestTable.COLUMN_RESULT + " INTEGER, " +
                CalculatorContract.QuestionRestTable.COLUMN_REST + " INTEGER " +
                ")";

        db.execSQL(SQL_CREATE_QUESTIONS_REST_TABLE);
        fillQuestionsRestTable();
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS " + CalculatorContract.QuestionRestTable.TABLE_NAME);
        onCreate(db);
    }

    private void fillQuestionsRestTable() {
        DivideRestQuestions q1 = new DivideRestQuestions("13 : 3 = ", 4, 1);
        addQuestion(q1);
        DivideRestQuestions q2 = new DivideRestQuestions("34 : 7 = ", 4, 6);
        addQuestion(q2);
        DivideRestQuestions q3 = new DivideRestQuestions("29 : 3 = ", 9, 2);
        addQuestion(q3);
        DivideRestQuestions q4 = new DivideRestQuestions("88 : 9 = ", 9, 7);
        addQuestion(q4);
        DivideRestQuestions q5 = new DivideRestQuestions("5 : 3 = ", 1, 2);
        addQuestion(q5);
        DivideRestQuestions q6 = new DivideRestQuestions("76 : 8 = ", 9, 4);
        addQuestion(q6);
        DivideRestQuestions q7 = new DivideRestQuestions("25 : 4 = ", 6, 1);
        addQuestion(q7);
        DivideRestQuestions q8 = new DivideRestQuestions("65 : 8 = ", 8, 1);
        addQuestion(q8);
        DivideRestQuestions q9 = new DivideRestQuestions("70 : 8 = ", 8, 6);
        addQuestion(q9);
        DivideRestQuestions q10 = new DivideRestQuestions("43 : 6 = ", 7, 1);
        addQuestion(q10);
        DivideRestQuestions q11 = new DivideRestQuestions("34 : 6 = ", 5, 4);
        addQuestion(q11);
        DivideRestQuestions q12 = new DivideRestQuestions("31 : 7 = ", 4, 3);
        addQuestion(q12);
        DivideRestQuestions q13 = new DivideRestQuestions("77 : 10 = ", 7, 7);
        addQuestion(q13);
        DivideRestQuestions q14 = new DivideRestQuestions("25 : 3 = ", 8, 1);
        addQuestion(q14);
        DivideRestQuestions q15 = new DivideRestQuestions("11 : 5 = ", 2, 1);
        addQuestion(q15);
        DivideRestQuestions q16 = new DivideRestQuestions("91 : 9 = ", 10, 1);
        addQuestion(q16);
        DivideRestQuestions q17 = new DivideRestQuestions("27 : 4 = ", 6, 3);
        addQuestion(q17);
        DivideRestQuestions q18 = new DivideRestQuestions("34 : 10 = ", 3, 4);
        addQuestion(q18);
        DivideRestQuestions q19 = new DivideRestQuestions("13 : 7 = ", 1, 6);
        addQuestion(q19);
        DivideRestQuestions q20 = new DivideRestQuestions("41 : 5 = ", 8, 1);
        addQuestion(q20);
        DivideRestQuestions q21 = new DivideRestQuestions("67 : 7 = ", 9, 4);
        addQuestion(q21);
        DivideRestQuestions q22 = new DivideRestQuestions("20 : 3 = ", 6, 2);
        addQuestion(q22);
        DivideRestQuestions q23 = new DivideRestQuestions("54 : 8 = ", 6, 6);
        addQuestion(q23);
        DivideRestQuestions q24 = new DivideRestQuestions("11 : 4 = ", 2, 3);
        addQuestion(q24);
        DivideRestQuestions q25 = new DivideRestQuestions("14 : 6 = ", 2, 2);
        addQuestion(q25);
        DivideRestQuestions q26 = new DivideRestQuestions("27 : 8 = ", 3, 3);
        addQuestion(q26);
        DivideRestQuestions q27 = new DivideRestQuestions("5 : 2 = ", 2, 1);
        addQuestion(q27);
        DivideRestQuestions q28 = new DivideRestQuestions("23: 6 = ", 3, 5);
        addQuestion(q28);
        DivideRestQuestions q29 = new DivideRestQuestions("34 : 8 = ", 4, 2);
        addQuestion(q29);
        DivideRestQuestions q30 = new DivideRestQuestions("20 : 3 = ", 6, 2);
        addQuestion(q30);
        DivideRestQuestions q31 = new DivideRestQuestions("9 : 2 = ", 4, 1);
        addQuestion(q31);
        DivideRestQuestions q32 = new DivideRestQuestions("17 : 4 = ", 4, 1);
        addQuestion(q32);
        DivideRestQuestions q33 = new DivideRestQuestions("11 : 5 = ", 2, 1);
        addQuestion(q33);
        DivideRestQuestions q34 = new DivideRestQuestions("19 : 7 = ", 2, 5);
        addQuestion(q34);
        DivideRestQuestions q35 = new DivideRestQuestions("25 : 4 = ", 6, 1);
        addQuestion(q35);
        DivideRestQuestions q36 = new DivideRestQuestions("29 : 9 = ", 3, 2);
        addQuestion(q36);
        DivideRestQuestions q37 = new DivideRestQuestions("51 : 5 = ", 10, 1);
        addQuestion(q37);
        DivideRestQuestions q38 = new DivideRestQuestions("65 : 6 = ", 10, 5);
        addQuestion(q38);
        DivideRestQuestions q39 = new DivideRestQuestions("21 : 2 = ", 10, 1);
        addQuestion(q39);
        DivideRestQuestions q40 = new DivideRestQuestions("40 : 5 = ", 8, 0);
        addQuestion(q40);
        DivideRestQuestions q41 = new DivideRestQuestions("61 : 7 = ", 8, 5);
        addQuestion(q41);
        DivideRestQuestions q42 = new DivideRestQuestions("19 : 4 = ", 4, 3);
        addQuestion(q42);
        DivideRestQuestions q43 = new DivideRestQuestions("27 : 2 = ", 13, 1);
        addQuestion(q43);
        DivideRestQuestions q44 = new DivideRestQuestions("35 : 6 = ", 5, 5);
        addQuestion(q44);
        DivideRestQuestions q45 = new DivideRestQuestions("31 : 2 = ", 15, 1);
        addQuestion(q45);
        DivideRestQuestions q46 = new DivideRestQuestions("40 : 6 = ", 6, 4);
        addQuestion(q46);
        DivideRestQuestions q47 = new DivideRestQuestions("39 : 8 = ", 4, 7);
        addQuestion(q47);
        DivideRestQuestions q48 = new DivideRestQuestions("55 : 2 = ", 27, 1);
        addQuestion(q48);
        DivideRestQuestions q49 = new DivideRestQuestions("11 : 2 = ", 5, 1);
        addQuestion(q49);
        DivideRestQuestions q50 = new DivideRestQuestions("17 : 8 = ", 2, 1);
        addQuestion(q50);
        DivideRestQuestions q51 = new DivideRestQuestions("28 : 11 = ", 2, 7);
        addQuestion(q51);
        DivideRestQuestions q52 = new DivideRestQuestions("13 : 3 = ", 4, 1);
        addQuestion(q52);
        DivideRestQuestions q53 = new DivideRestQuestions("8 : 3 = ", 2, 2);
        addQuestion(q53);
        DivideRestQuestions q54 = new DivideRestQuestions("4 : 3 = ", 1, 1);
        addQuestion(q54);
        DivideRestQuestions q55 = new DivideRestQuestions("18 : 5 = ", 3, 3);
        addQuestion(q55);
        DivideRestQuestions q56 = new DivideRestQuestions("34 : 3 = ", 11, 1);
        addQuestion(q56);
        DivideRestQuestions q57 = new DivideRestQuestions("29 : 4 = ", 7, 1);
        addQuestion(q57);
        DivideRestQuestions q58 = new DivideRestQuestions("14 : 5 = ", 2, 4);
        addQuestion(q58);
        DivideRestQuestions q59 = new DivideRestQuestions("28 : 8 = ", 3, 4);
        addQuestion(q59);
        DivideRestQuestions q60 = new DivideRestQuestions("43 : 6 = ", 7, 1);
        addQuestion(q60);
        DivideRestQuestions q61 = new DivideRestQuestions("57 : 8 = ", 7, 1);
        addQuestion(q61);
        DivideRestQuestions q62 = new DivideRestQuestions("57 : 7 = ", 8, 1);
        addQuestion(q62);
        DivideRestQuestions q63 = new DivideRestQuestions("20 : 6 = ", 3, 2);
        addQuestion(q63);
        DivideRestQuestions q64 = new DivideRestQuestions("23 : 9 = ", 2, 5);
        addQuestion(q64);
        DivideRestQuestions q65 = new DivideRestQuestions("61 : 7 = ", 8, 5);
        addQuestion(q65);
        DivideRestQuestions q66 = new DivideRestQuestions("43 : 5 = ", 8, 3);
        addQuestion(q66);
        DivideRestQuestions q67 = new DivideRestQuestions("19 : 9 = ", 2, 1);
        addQuestion(q67);
        DivideRestQuestions q68 = new DivideRestQuestions("13 : 2 = ", 6, 1);
        addQuestion(q68);
        DivideRestQuestions q69 = new DivideRestQuestions("9 : 6 = ", 1, 3);
        addQuestion(q69);
        DivideRestQuestions q70 = new DivideRestQuestions("12 : 5 = ", 2, 2);
        addQuestion(q70);
        DivideRestQuestions q71 = new DivideRestQuestions("5 : 3 = ", 1, 2);
        addQuestion(q71);
        DivideRestQuestions q72 = new DivideRestQuestions("22 : 5 = ", 4, 2);
        addQuestion(q72);
        DivideRestQuestions q73 = new DivideRestQuestions("10 : 4 = ", 2, 2);
        addQuestion(q73);
        DivideRestQuestions q74 = new DivideRestQuestions("22 : 7 = ", 3, 1);
        addQuestion(q74);
        DivideRestQuestions q75 = new DivideRestQuestions("31 : 8 = ", 3, 7);
        addQuestion(q75);
        DivideRestQuestions q76 = new DivideRestQuestions("33 : 4 = ", 8, 1);
        addQuestion(q76);
        DivideRestQuestions q77 = new DivideRestQuestions("51 : 5 = ", 10, 1);
        addQuestion(q77);
        DivideRestQuestions q78 = new DivideRestQuestions("54 : 5 = ", 10, 4);
        addQuestion(q78);
        DivideRestQuestions q79 = new DivideRestQuestions("3 : 4 = ", 0, 3);
        addQuestion(q79);
        DivideRestQuestions q80 = new DivideRestQuestions("15 : 2 = ", 7, 1);
        addQuestion(q80);
        DivideRestQuestions q81 = new DivideRestQuestions("35 : 8 = ", 4, 3);
        addQuestion(q81);
        DivideRestQuestions q82 = new DivideRestQuestions("15 : 9 = ", 1, 6);
        addQuestion(q82);
        DivideRestQuestions q83 = new DivideRestQuestions("13 : 6 = ", 2, 1);
        addQuestion(q83);
        DivideRestQuestions q84 = new DivideRestQuestions("25 : 10 = ", 2, 5);
        addQuestion(q84);
        DivideRestQuestions q85 = new DivideRestQuestions("10 : 3 = ", 3, 1);
        addQuestion(q85);
        DivideRestQuestions q86 = new DivideRestQuestions("7 : 2 = ", 3, 1);
        addQuestion(q86);
        DivideRestQuestions q87 = new DivideRestQuestions("9 : 4 = ", 2, 1);
        addQuestion(q87);
        DivideRestQuestions q88 = new DivideRestQuestions("20 : 8 = ", 2, 4);
        addQuestion(q88);
        DivideRestQuestions q89 = new DivideRestQuestions("6 : 4 = ", 1, 2);
        addQuestion(q89);
        DivideRestQuestions q90 = new DivideRestQuestions("27 : 4 = ", 6, 3);
        addQuestion(q90);
        DivideRestQuestions q91 = new DivideRestQuestions("47 : 7 = ", 6, 5);
        addQuestion(q91);
        DivideRestQuestions q92 = new DivideRestQuestions("14 : 4 = ", 3, 2);
        addQuestion(q92);
        DivideRestQuestions q93 = new DivideRestQuestions("13 : 6 = ", 2, 1);
        addQuestion(q93);
        DivideRestQuestions q94 = new DivideRestQuestions("17 : 8 = ", 2, 1);
        addQuestion(q94);
        DivideRestQuestions q95 = new DivideRestQuestions("7 : 4 = ", 1, 3);
        addQuestion(q95);
        DivideRestQuestions q96 = new DivideRestQuestions("27 : 8 = ", 3, 3);
        addQuestion(q96);
        DivideRestQuestions q97 = new DivideRestQuestions("27 : 9 = ", 3, 0);
        addQuestion(q97);
        DivideRestQuestions q98 = new DivideRestQuestions("7 : 8 = ", 0, 7);
        addQuestion(q98);
        DivideRestQuestions q99 = new DivideRestQuestions("31 : 4 = ", 7, 3);
        addQuestion(q99);
        DivideRestQuestions q100 = new DivideRestQuestions("101 : 10 = ", 10, 1);
        addQuestion(q100);
        DivideRestQuestions q101 = new DivideRestQuestions("93 : 6 = ", 15, 3);
        addQuestion(q101);
        DivideRestQuestions q102 = new DivideRestQuestions("52 : 7 = ", 7, 3);
        addQuestion(q102);
        DivideRestQuestions q103 = new DivideRestQuestions("11 : 3 = ", 3, 2);
        addQuestion(q103);
        DivideRestQuestions q104 = new DivideRestQuestions("36 : 5 = ", 7, 1);
        addQuestion(q104);
        DivideRestQuestions q105 = new DivideRestQuestions("79 : 7 = ", 11, 2);
        addQuestion(q105);
        DivideRestQuestions q106 = new DivideRestQuestions("95 : 6 = ", 15, 5);
        addQuestion(q106);
        DivideRestQuestions q107 = new DivideRestQuestions("65 : 3 = ", 21, 2);
        addQuestion(q107);
        DivideRestQuestions q108 = new DivideRestQuestions("80 : 7 = ", 11, 3);
        addQuestion(q108);
        DivideRestQuestions q109 = new DivideRestQuestions("36 : 5 = ", 7, 1);
        addQuestion(q109);
        DivideRestQuestions q110 = new DivideRestQuestions("56 : 3 = ", 18, 2);
        addQuestion(q110);
        DivideRestQuestions q111 = new DivideRestQuestions("65 : 2 = ", 32, 1);
        addQuestion(q111);
        DivideRestQuestions q112 = new DivideRestQuestions("27 : 2 = ", 13, 1);
        addQuestion(q112);
        DivideRestQuestions q113 = new DivideRestQuestions("25 : 2 = ", 12, 1);
        addQuestion(q113);
        DivideRestQuestions q114 = new DivideRestQuestions("10 : 4 = ", 2, 2);
        addQuestion(q114);
        DivideRestQuestions q115 = new DivideRestQuestions("20 : 3 = ", 6, 2);
        addQuestion(q115);
        DivideRestQuestions q116 = new DivideRestQuestions("41 : 5 = ", 8, 1);
        addQuestion(q116);
        DivideRestQuestions q117 = new DivideRestQuestions("7 : 5 = ", 1, 2);
        addQuestion(q117);
        DivideRestQuestions q118 = new DivideRestQuestions("46 : 3 = ", 15, 1);
        addQuestion(q118);
        DivideRestQuestions q119 = new DivideRestQuestions("39 : 4 = ", 9, 3);
        addQuestion(q119);
        DivideRestQuestions q120 = new DivideRestQuestions("32 : 6 = ", 5, 2);
        addQuestion(q120);
        DivideRestQuestions q121 = new DivideRestQuestions("61 : 7 = ", 8, 5);
        addQuestion(q121);
        DivideRestQuestions q122 = new DivideRestQuestions("85 : 2 = ", 42, 1);
        addQuestion(q122);
        DivideRestQuestions q123 = new DivideRestQuestions("66 : 7 = ", 9, 3);
        addQuestion(q123);
        DivideRestQuestions q124 = new DivideRestQuestions("32 : 3 = ", 10, 2);
        addQuestion(q124);
        DivideRestQuestions q125 = new DivideRestQuestions("88 : 9 = ", 9, 7);
        addQuestion(q125);
        DivideRestQuestions q126 = new DivideRestQuestions("76 : 6 = ", 12, 4);
        addQuestion(q126);
        DivideRestQuestions q127 = new DivideRestQuestions("21 : 4 = ", 5, 1);
        addQuestion(q127);
        DivideRestQuestions q128 = new DivideRestQuestions("50 : 6 = ", 8, 2);
        addQuestion(q128);
        DivideRestQuestions q129 = new DivideRestQuestions("89 : 6 = ", 14, 5);
        addQuestion(q129);
        DivideRestQuestions q130 = new DivideRestQuestions("97 : 6 = ", 16, 1);
        addQuestion(q130);
        DivideRestQuestions q131 = new DivideRestQuestions("46 : 3 = ", 15, 1);
        addQuestion(q131);
        DivideRestQuestions q132 = new DivideRestQuestions("47 : 4 = ", 11, 3);
        addQuestion(q132);
        DivideRestQuestions q133 = new DivideRestQuestions("7 : 2 = ", 3, 1);
        addQuestion(q133);
        DivideRestQuestions q134 = new DivideRestQuestions("58 : 9 = ", 6, 4);
        addQuestion(q134);
        DivideRestQuestions q135 = new DivideRestQuestions("76 : 6 = ", 12, 4);
        addQuestion(q135);
        DivideRestQuestions q136 = new DivideRestQuestions("67 : 6 = ", 11, 1);
        addQuestion(q136);
        DivideRestQuestions q137 = new DivideRestQuestions("81 : 4 = ", 20, 1);
        addQuestion(q137);
        DivideRestQuestions q138 = new DivideRestQuestions("28 : 3 = ", 9, 1);
        addQuestion(q138);
        DivideRestQuestions q139 = new DivideRestQuestions("34 : 5 = ", 6, 4);
        addQuestion(q139);
        DivideRestQuestions q140 = new DivideRestQuestions("7 : 3 = ", 2, 1);
        addQuestion(q140);
        DivideRestQuestions q141 = new DivideRestQuestions("77 : 8 = ", 9, 5);
        addQuestion(q141);
        DivideRestQuestions q142 = new DivideRestQuestions("61 : 3 = ", 20, 1);
        addQuestion(q142);
        DivideRestQuestions q143 = new DivideRestQuestions("37 : 9 = ", 4, 1);
        addQuestion(q143);
        DivideRestQuestions q144 = new DivideRestQuestions("18 : 8 = ", 2, 2);
        addQuestion(q144);
        DivideRestQuestions q145 = new DivideRestQuestions("58 : 3 = ", 19, 1);
        addQuestion(q145);
        DivideRestQuestions q146 = new DivideRestQuestions("61 : 4 = ", 15, 1);
        addQuestion(q146);
        DivideRestQuestions q147 = new DivideRestQuestions("8 : 3 = ", 2, 2);
        addQuestion(q147);
        DivideRestQuestions q148 = new DivideRestQuestions("27 : 5 = ", 5, 2);
        addQuestion(q148);
        DivideRestQuestions q149 = new DivideRestQuestions("97 : 7 = ", 13, 6);
        addQuestion(q149);
        DivideRestQuestions q150 = new DivideRestQuestions("73 : 6 = ", 12, 1);
        addQuestion(q150);
        DivideRestQuestions q151 = new DivideRestQuestions("94 : 5 = ", 18, 4);
        addQuestion(q151);
        DivideRestQuestions q152 = new DivideRestQuestions("95 : 3 = ", 31, 2);
        addQuestion(q152);
        DivideRestQuestions q153 = new DivideRestQuestions("17 : 3 = ", 5, 2);
        addQuestion(q153);
        DivideRestQuestions q154 = new DivideRestQuestions("95 : 4 = ", 23, 3);
        addQuestion(q154);
        DivideRestQuestions q155 = new DivideRestQuestions("89 : 5 = ", 17, 4);
        addQuestion(q155);
        DivideRestQuestions q156 = new DivideRestQuestions("51 : 7 = ", 7, 2);
        addQuestion(q156);
        DivideRestQuestions q157 = new DivideRestQuestions("87 : 6 = ", 14, 3);
        addQuestion(q157);
        DivideRestQuestions q158 = new DivideRestQuestions("28 : 9 = ", 3, 1);
        addQuestion(q158);
        DivideRestQuestions q159 = new DivideRestQuestions("29 : 6 = ", 4, 5);
        addQuestion(q159);
        DivideRestQuestions q160 = new DivideRestQuestions("16 : 9 = ", 1, 7);
        addQuestion(q160);
        DivideRestQuestions q161 = new DivideRestQuestions("11 : 9 = ", 1, 2);
        addQuestion(q161);
        DivideRestQuestions q162 = new DivideRestQuestions("12 : 8 = ", 1, 4);
        addQuestion(q162);
        DivideRestQuestions q163 = new DivideRestQuestions("39 : 5 = ", 7, 4);
        addQuestion(q163);
        DivideRestQuestions q164 = new DivideRestQuestions("39 : 6 = ", 6, 3);
        addQuestion(q164);
        DivideRestQuestions q165 = new DivideRestQuestions("39 : 9 = ", 4, 3);
        addQuestion(q165);
        DivideRestQuestions q166 = new DivideRestQuestions("76 : 8 = ", 9, 4);
        addQuestion(q166);
        DivideRestQuestions q167 = new DivideRestQuestions("87 : 2 = ", 43, 1);
        addQuestion(q167);
        DivideRestQuestions q168 = new DivideRestQuestions("9 : 7 = ", 1, 2);
        addQuestion(q168);
        DivideRestQuestions q169 = new DivideRestQuestions("41 : 2 = ", 20, 1);
        addQuestion(q169);
        DivideRestQuestions q170 = new DivideRestQuestions("79 : 9 = ", 8, 7);
        addQuestion(q170);
        DivideRestQuestions q171 = new DivideRestQuestions("25 : 2 = ", 12, 1);
        addQuestion(q171);
        DivideRestQuestions q172 = new DivideRestQuestions("33 : 4 = ", 8, 1);
        addQuestion(q172);
        DivideRestQuestions q173 = new DivideRestQuestions("61 : 4 = ", 15, 1);
        addQuestion(q173);
        DivideRestQuestions q174 = new DivideRestQuestions("77 : 4 = ", 19, 1);
        addQuestion(q174);
        DivideRestQuestions q175 = new DivideRestQuestions("23 : 7 = ", 3, 2);
        addQuestion(q175);
        DivideRestQuestions q176 = new DivideRestQuestions("99 : 5 = ", 19, 4);
        addQuestion(q176);
        DivideRestQuestions q177 = new DivideRestQuestions("27 : 6 = ", 4, 3);
        addQuestion(q177);
        DivideRestQuestions q178 = new DivideRestQuestions("75 : 4 = ", 18, 3);
        addQuestion(q178);
        DivideRestQuestions q179 = new DivideRestQuestions("26 : 5 = ", 5, 1);
        addQuestion(q179);
        DivideRestQuestions q180 = new DivideRestQuestions("75 : 8 = ", 9, 3);
        addQuestion(q180);
        DivideRestQuestions q181 = new DivideRestQuestions("33 : 9 = ", 3, 6);
        addQuestion(q181);
        DivideRestQuestions q182 = new DivideRestQuestions("17 : 7 = ", 2, 3);
        addQuestion(q182);
        DivideRestQuestions q183 = new DivideRestQuestions("25 : 4 = ", 6, 1);
        addQuestion(q183);
        DivideRestQuestions q184 = new DivideRestQuestions("42 : 4 = ", 10, 2);
        addQuestion(q184);
        DivideRestQuestions q185 = new DivideRestQuestions("86 : 5 = ", 17, 1);
        addQuestion(q185);
        DivideRestQuestions q186 = new DivideRestQuestions("94 : 8 = ", 11, 6);
        addQuestion(q186);
        DivideRestQuestions q187 = new DivideRestQuestions("16 : 7 = ", 2, 2);
        addQuestion(q187);
        DivideRestQuestions q188 = new DivideRestQuestions("70 : 6 = ", 11, 4);
        addQuestion(q188);
        DivideRestQuestions q189 = new DivideRestQuestions("72 : 5 = ", 14, 2);
        addQuestion(q189);
        DivideRestQuestions q190 = new DivideRestQuestions("81 : 6 = ", 13, 3);
        addQuestion(q190);
        DivideRestQuestions q191 = new DivideRestQuestions("34 : 6 = ", 5, 4);
        addQuestion(q191);
        DivideRestQuestions q192 = new DivideRestQuestions("70 : 6 = ", 11, 4);
        addQuestion(q192);
        DivideRestQuestions q193 = new DivideRestQuestions("47 : 2 = ", 23, 1);
        addQuestion(q193);
        DivideRestQuestions q194 = new DivideRestQuestions("95 : 8 = ", 11, 7);
        addQuestion(q194);
        DivideRestQuestions q195 = new DivideRestQuestions("25 : 9 = ", 2, 7);
        addQuestion(q195);
        DivideRestQuestions q196 = new DivideRestQuestions("15 : 2 = ", 7, 1);
        addQuestion(q196);
        DivideRestQuestions q197 = new DivideRestQuestions("31 : 9 = ", 3, 4);
        addQuestion(q197);
        DivideRestQuestions q198 = new DivideRestQuestions("22 : 7 = ", 3, 1);
        addQuestion(q198);
        DivideRestQuestions q199 = new DivideRestQuestions("11 : 3 = ", 3, 2);
        addQuestion(q199);
        DivideRestQuestions q200 = new DivideRestQuestions("19 : 8 = ", 2, 3);
        addQuestion(q200);
        DivideRestQuestions q201 = new DivideRestQuestions("95 : 6 = ", 15, 5);
        addQuestion(q201);
        DivideRestQuestions q202 = new DivideRestQuestions("63 : 6 = ", 10, 3);
        addQuestion(q202);
        DivideRestQuestions q203 = new DivideRestQuestions("42 : 9 = ", 4, 6);
        addQuestion(q203);
        DivideRestQuestions q204 = new DivideRestQuestions("34 : 3 = ", 11, 1);
        addQuestion(q204);
        DivideRestQuestions q205 = new DivideRestQuestions("87 : 7 = ", 12, 3);
        addQuestion(q205);
        DivideRestQuestions q206 = new DivideRestQuestions("97 : 6 = ", 16, 1);
        addQuestion(q206);
        DivideRestQuestions q207 = new DivideRestQuestions("41 : 7 = ", 5, 6);
        addQuestion(q207);
        DivideRestQuestions q208 = new DivideRestQuestions("55 : 4 = ", 13, 3);
        addQuestion(q208);
        DivideRestQuestions q209 = new DivideRestQuestions("62 : 5 = ", 12, 2);
        addQuestion(q209);
        DivideRestQuestions q210 = new DivideRestQuestions("84 : 8 = ", 10, 4);
        addQuestion(q210);
        DivideRestQuestions q211 = new DivideRestQuestions("54 : 5 = ", 10, 4);
        addQuestion(q211);
        DivideRestQuestions q212 = new DivideRestQuestions("23 : 6 = ", 3, 5);
        addQuestion(q212);
        DivideRestQuestions q213 = new DivideRestQuestions("7 : 5 = ", 1, 2);
        addQuestion(q213);
        DivideRestQuestions q214 = new DivideRestQuestions("15 : 8 = ", 1, 7);
        addQuestion(q214);
        DivideRestQuestions q215 = new DivideRestQuestions("47 : 9 = ", 5, 2);
        addQuestion(q215);
        DivideRestQuestions q216 = new DivideRestQuestions("58 : 6 = ", 9, 4);
        addQuestion(q216);
        DivideRestQuestions q217 = new DivideRestQuestions("26 : 6 = ", 4, 2);
        addQuestion(q217);
        DivideRestQuestions q218 = new DivideRestQuestions("67 : 8 = ", 8, 3);
        addQuestion(q218);
        DivideRestQuestions q219 = new DivideRestQuestions("39 : 4 = ", 9, 3);
        addQuestion(q219);
        DivideRestQuestions q220 = new DivideRestQuestions("62 : 7 = ", 8, 6);
        addQuestion(q220);
        DivideRestQuestions q221 = new DivideRestQuestions("11 : 2 = ", 5, 1);
        addQuestion(q221);
        DivideRestQuestions q222 = new DivideRestQuestions("23 : 7 = ", 3, 2);
        addQuestion(q222);
        DivideRestQuestions q223 = new DivideRestQuestions("64 : 9 = ", 7, 1);
        addQuestion(q223);
        DivideRestQuestions q224 = new DivideRestQuestions("34 : 8 = ", 4, 2);
        addQuestion(q224);
        DivideRestQuestions q225 = new DivideRestQuestions("46 : 7 = ", 6, 4);
        addQuestion(q225);
        DivideRestQuestions q226 = new DivideRestQuestions("55 : 2 = ", 27, 1);
        addQuestion(q226);
        DivideRestQuestions q227 = new DivideRestQuestions("44 : 7 = ", 6, 2);
        addQuestion(q227);
        DivideRestQuestions q228 = new DivideRestQuestions("41 : 4 = ", 10, 1);
        addQuestion(q228);
        DivideRestQuestions q229 = new DivideRestQuestions("24 : 7 = ", 3, 3);
        addQuestion(q229);
        DivideRestQuestions q230 = new DivideRestQuestions("61 : 3 = ", 20, 1);
        addQuestion(q230);
        DivideRestQuestions q231 = new DivideRestQuestions("43 : 2 = ", 21, 1);
        addQuestion(q231);
        DivideRestQuestions q232 = new DivideRestQuestions("45 : 6 = ", 7, 3);
        addQuestion(q232);
        DivideRestQuestions q233 = new DivideRestQuestions("45 : 2 = ", 22, 1);
        addQuestion(q233);
        DivideRestQuestions q234 = new DivideRestQuestions("28 : 6 = ", 4, 4);
        addQuestion(q234);
        DivideRestQuestions q235 = new DivideRestQuestions("13 : 3 = ", 4, 1);
        addQuestion(q235);
        DivideRestQuestions q236 = new DivideRestQuestions("20 : 7 = ", 2, 6);
        addQuestion(q236);
        DivideRestQuestions q237 = new DivideRestQuestions("25 : 9 = ", 2, 7);
        addQuestion(q237);
        DivideRestQuestions q238 = new DivideRestQuestions("45 : 7 = ", 6, 3);
        addQuestion(q238);
        DivideRestQuestions q239 = new DivideRestQuestions("85 : 7 = ", 12, 1);
        addQuestion(q239);
        DivideRestQuestions q240 = new DivideRestQuestions("61 : 2 = ", 30, 1);
        addQuestion(q240);



    }

    private void addQuestion(DivideRestQuestions questions){
        ContentValues cv = new ContentValues();
        cv.put(CalculatorContract.QuestionRestTable.COLUMN_QUESTION, questions.getQuestion());
        cv.put(CalculatorContract.QuestionRestTable.COLUMN_RESULT, questions.getResult());
        cv.put(CalculatorContract.QuestionRestTable.COLUMN_REST, questions.getRest());

        db.insert(CalculatorContract.QuestionRestTable.TABLE_NAME, null, cv);
    }

    public List<DivideRestQuestions> getAllDivideRestQuestions() {
        List<DivideRestQuestions> divideRestQuestionsList = new ArrayList<>();
        db = getReadableDatabase();
        Cursor c = db.rawQuery("SELECT * FROM " + CalculatorContract.QuestionRestTable.TABLE_NAME, null);
        if(c.moveToFirst()) {
            do {
                DivideRestQuestions questions = new DivideRestQuestions();
                questions.setQuestion(c.getString(c.getColumnIndex(CalculatorContract.QuestionRestTable.COLUMN_QUESTION)));
                questions.setResult(c.getInt(c.getColumnIndex(CalculatorContract.QuestionRestTable.COLUMN_RESULT)));
                questions.setRest(c.getInt(c.getColumnIndex(CalculatorContract.QuestionRestTable.COLUMN_REST)));
                divideRestQuestionsList.add(questions);
            }while(c.moveToNext());
        }
        c.close();
        return divideRestQuestionsList;
    }
}
